name: AWS and GITHUB

on:
  push:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  callerIdentity:
    uses: alphaveer/docker-awscli/.github/workflows/terraform.yaml@master
    with:
      workspace: dev
    secrets: inherit
