name: AWS and GITHUB
on:
  push:
  workflow_dispatch:
env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
permissions:
      id-token: write
      contents: read
jobs:
  callerIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ env.GITHUB_REPOSITORY }}
          aws-region: ${{ env.AWS_REGION }}
      - name:  test credentials
        run: |
          aws sts get-caller-identity
