name: Terrafom

on:
  push:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read
    
jobs:
  Terraform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, prod, test]
    environment: 
      name: ${{ matrix.environment }}
      url: https://github.com
    steps:
      
