name: "Terraform"
on:
  push:
  workflow_dispatch:

jobs:
  Plan_Development:
    uses: alphaveer/docker-awscli/.github/workflows/plan.yaml@master
    with:
      gh_environment: dev

  Deploy_Development:
    needs: [Plan_Development]
    uses: alphaveer/docker-awscli/.github/workflows/apply.yaml@master
    with:
      gh_environment: dev

  Plan_Test:
    uses: alphaveer/docker-awscli/.github/workflows/plan.yaml@master
    with:
      gh_environment: test

  Deploy_Test:
    needs: [Plan_Test]
    uses: alphaveer/docker-awscli/.github/workflows/apply.yaml@master
    with:
      gh_environment: test

  Plan_Prod:
    uses: alphaveer/docker-awscli/.github/workflows/plan.yaml@master
    with:
      gh_environment: prod

  Deploy_Prod:
    needs: [Plan_Prod]
    uses: alphaveer/docker-awscli/.github/workflows/apply.yaml@master
    with:
      gh_environment: prod
